### PR TITLE
Cache metadata and JWK set HTTP responses

### LINKED ISSUE #3: Caching of JWT keys
Cache the JWT keys by default.

### LINKED ISSUE #4: Caching of metaData URI
Cache the meta data response

### PR DESCRIPTION
**Pull request by caleblloyd**
- Fixes #3 
  - Caches JWK Set for 5 minutes 
- Fixes #4 
  - Caches MetaData for 5 minutes

**100 Calls takes ~20s Before Caching**

```
2018/07/27 01:38:32 Initial VerifyIdToken Call  : 252.485113ms
2018/07/27 01:38:51 Next 100 VerifyIdToken Calls: 19.23939512s
```

**100 Calls takes ~20ms After Caching**

```
2018/07/27 01:38:22 Initial VerifyIdToken Call  : 234.398669ms
2018/07/27 01:38:22 Next 100 VerifyIdToken Calls: 18.013289ms
```

---

That's a 1000x speed-up if they're both cache hits :smile:

### CODE REVIEW

**Comment by robertjd** [comment]
Hi @caleblloyd !  This is great, thanks for this.  We do depend on secret environment variables in Travis, so fork PRs will fail.

We're currently busy with our Go SDK, so it might take us some time to review this.  We're also having an internal discussion on what the cache lifetimes should be (we want to make sure we pick a default that we'll use across all our verifiers).

**Comment by bretterer** [comment]
Hi @caleblloyd ! Thanks for your pull request.

Before we can move forward with reviewing/merging your PR, please take a moment to read and sign a Contributor License Agreement (CLA).

Please visit developer.okta.com/cla to sign.

Then, reply here (“Signed”) so we can proceed.

Thanks!

**Comment by caleblloyd** [comment]
Signed

**Comment by jeanhalle** [comment]
@bretterer  Any updates on that topic?

**Pull request merged**
