### PR TITLE
Make Audience validation optional

### LINKED ISSUE #115: Library forces you to validate audience/aud claim
When using the `JwtVerifier` struct to validate ID tokens and Access tokens, you are forced to provide a value for the `aud` claim. I don't want to validate the `aud` claim and there is no way to turn this off.

### PR DESCRIPTION
**Pull request by ianling**
Fixes #115 

Mostly a copy+paste of what is in `validateClientId`

### CODE REVIEW

**Review by duytiennguyen-okta — APPROVED** [review]

**Review by monde — APPROVED** [review]
:shipit:
See explanation:

https://github.com/okta/okta-jwt-verifier-golang/issues/115#issuecomment-2327343286

**Comment by monde** [comment]
@ianling we have merge protections against unsigned commits. Can you set up commit signing (^^^ [Learn more about signing commits.](https://docs.github.com/authentication/managing-commit-signature-verification/about-commit-signature-verification)) . After you do that you can rewrite your commit history with the new signature. I've used this technique to do that before https://stackoverflow.com/questions/3042437/how-can-i-change-the-commit-author-for-a-single-commit . If you do that then you'd force push that back up in your branch and we'd have to approve this PR again. That said, it may just be easier doing a new brach and commit with your new signature and making a new PR from that if your not comfortable going down the rabbit hole of power git usage.

**Comment by ianling** [comment]
@monde 👍 signed the commit

**Comment by monde** [comment]
released https://github.com/okta/okta-jwt-verifier-golang/releases/tag/v2.1.0

**Pull request merged**
