### PR TITLE
Make discovery document cache configurable

### PR DESCRIPTION
**Pull request by adw1n**
okta-jwt-verifier-golang uses two global caches - `jwkSetCache` in `adaptor` and `metaDataCache` in `jwtverifier`. Users are able to tune the adaptor's cache but they can't change the `metaDataCache`. I propose we move the `metaDataCache` to `oidc.go` to give users the ability to change the cache by providing their own `Discovery` object when creating `JwtVerifier`.

Personally I'm interested in providing my own `Discovery` and `Adaptor` objects to `JwtVerifier` in order to modify the cache duration and to fix handling of signing keys rotation.

### CODE REVIEW

**Comment by adw1n** [comment]
@bretterer would you be willing to accept these changes?

**Comment by bretterer** [comment]
@adw1n I am looking into this.  Could you please file a CLA with us to help the process if these changes will end up being accepted?

**Comment by adw1n** [comment]
@bretterer I submitted the CLA

**Comment by monde** [comment]
@adw1n @caleblloyd we released a customizable cache via a "Cacher" interface in v1.2.0 of the verifier https://github.com/okta/okta-jwt-verifier-golang/#customizable-resource-cache . Given that, what would you like to do with this PR? Maybe I could encourage you to refactor it to be encapsulated as a Cacher that we can include in the project? Let me know. Thanks!

**Pull request closed without merging**
