### PR TITLE
add PKCE code verifier utility

### LINKED ISSUE #80: Add utilities for PKCE code challenge
Hello folks, do you think adding util to generate PKCE code challenge (base64 encoded sha256) will be applicable for this lib? If so I can create a PR./ Currently it needs to be done like this

```go
// Create the PKCE code verifier and code challenge
oauthCodeVerifier := randstr.Hex(50)
// create sha256 hash of the code verifier
oauthCodeChallenge := base64.StdEncoding.EncodeToString([]byte(fmt.Sprintf("%x", sha256.Sum256([]byte(oauthCodeVerifier)))))
oauthCodeChallenge = strings.Replace(oauthCodeChallenge, "+", "-", -1)
oauthCodeChallenge = strings.Replace(oauthCodeChallenge, "/", "_", -1)
oauthCodeChallenge = strings.Replace(oauthCodeChallenge, "=", "", -1)
```

### PR DESCRIPTION
**Pull request by deepu105**
Adds PKCE code verifier and challenge utility

Addresses and closes #80

### CODE REVIEW

**Comment by monde** [comment]
Awesome, thank you @deepu105 I'll give this a review later today.

**Comment by monde** [comment]
@deepu105 can add something in the readme highlighting the presence of the pcke code verifier? This code looks good to me otherwise.

**Comment by deepu105** [comment]
seems like travis test fails are not related to this PR but some env vars missing for existing tests

**Review by monde — APPROVED** [review]
:shipit: 😎

**Comment by monde** [comment]
> > seems like travis test fails are not related to this PR but some env vars missing for existing tests
> 
> Right, CI doesn't run with the private Okta ENV variables when the run is against a remote/clone repo.

@deepu105 I have to make a branch in okta/okta-jwt-verifier-golang and cherry pick these commits in. Admittedly a tedious workflow to take contributions from outside repos.

**Comment by deepu105** [comment]
whaaaat!!! that sucks. But ya whatever works for you

**Comment by monde** [comment]
released https://github.com/okta/okta-jwt-verifier-golang/pull/82

**Pull request closed without merging**
